import type { Session } from "@kairohq/shared";
import { describe, expect, it } from "vitest";
import { renderTimeline } from "./timeline.ts";

describe("renderTimeline", () => {
  it("renders sessions newest first with stable markdown", () => {
    expect(renderTimeline([storageSession, authSession])).toMatchInlineSnapshot(`
      "# Project Timeline

      > Auto-generated by Kairo. Edits will be preserved across regenerations where possible.

      ## 2026-05-15 -> 2026-05-18 · Authentication Rewrite

      **Intent:** refactor · **Areas:** \`packages/auth\`, \`apps/web/middleware\`

      - Consolidated auth validation into one package.
      - Switched persistence to httpOnly refresh rotation.

      **Architecture impact**

      - One verifier now serves web and desktop.
      - Removed duplicate middleware boundaries.

      [full session ->](sessions/2026-05-15-auth-rewrite.md)

      ---

      ## 2026-05-12 · Storage layer bootstrap

      **Intent:** feature · **Areas:** \`packages/core/event-store\`

      - Introduced SQLite event storage.

      [full session ->](sessions/2026-05-12-storage-bootstrap.md)
      "
    `);
  });

  it("renders an empty timeline", () => {
    expect(renderTimeline([])).toMatchInlineSnapshot(`
      "# Project Timeline

      > Auto-generated by Kairo. Edits will be preserved across regenerations where possible.

      No sessions reconstructed yet.
      "
    `);
  });
});

const authSession: Session = {
  id: "11111111-1111-4111-8111-111111111111",
  projectId: "project-1",
  title: "Authentication Rewrite",
  slug: "2026-05-15-auth-rewrite",
  startedAt: "2026-05-15T09:12:00.000Z",
  endedAt: "2026-05-18T17:40:00.000Z",
  intent: "refactor",
  themes: ["auth", "middleware", "token-rotation"],
  affectedAreas: ["packages/auth", "apps/web/middleware"],
  commitShas: ["a111111", "b222222"],
  files: ["packages/auth/index.ts", "apps/web/middleware/auth.ts"],
  summary:
    "Consolidated auth validation into one package.\nSwitched persistence to httpOnly refresh rotation.",
  architectureImpact:
    "One verifier now serves web and desktop.\nRemoved duplicate middleware boundaries.",
  eventIds: ["event-1"],
};

const storageSession: Session = {
  id: "22222222-2222-4222-8222-222222222222",
  projectId: "project-1",
  title: "Storage layer bootstrap",
  slug: "2026-05-12-storage-bootstrap",
  startedAt: "2026-05-12T10:00:00.000Z",
  endedAt: "2026-05-12T11:30:00.000Z",
  intent: "feature",
  themes: ["storage"],
  affectedAreas: ["packages/core/event-store"],
  commitShas: ["c333333"],
  files: ["packages/core/src/event-store/event-store.ts"],
  summary: "Introduced SQLite event storage.",
  architectureImpact: null,
  eventIds: ["event-2"],
};
