import type { Session } from "@kairo/shared";
import { renderDateRange, renderInlineCodeList, renderSummaryBullets } from "./format.ts";

const HEADER = [
  "# Project Timeline",
  "",
  "> Auto-generated by Kairo. Edits will be preserved across regenerations where possible.",
  "",
  "",
];

export function renderTimeline(sessions: Session[]): string {
  const sorted = [...sessions].sort((a, b) => b.startedAt.localeCompare(a.startedAt));

  if (sorted.length === 0) {
    return `${HEADER.join("\n")}No sessions reconstructed yet.\n`;
  }

  const entries = sorted.map(renderTimelineEntry);
  return `${HEADER.join("\n")}${entries.join("\n---\n\n")}`;
}

function renderTimelineEntry(session: Session): string {
  const areas =
    session.affectedAreas.length > 0 ? renderInlineCodeList(session.affectedAreas) : "none";
  const lines = [
    `## ${renderDateRange(session)} · ${session.title}`,
    "",
    `**Intent:** ${session.intent} · **Areas:** ${areas}`,
    "",
    ...renderSummaryBullets(session.summary).map((line) => `- ${line}`),
  ];

  if (session.architectureImpact) {
    lines.push(
      "",
      "**Architecture impact**",
      "",
      ...renderSummaryBullets(session.architectureImpact).map((line) => `- ${line}`),
    );
  }

  lines.push("", `[full session ->](sessions/${session.slug}.md)`, "");
  return lines.join("\n");
}
