import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { EventStore, Workspace } from "@kairo/core";
import type { ArchitectureShift } from "@kairo/shared";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { renderReflectionReport, runReflect } from "./reflect.ts";

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "kairo-cli-reflect-"));
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("runReflect", () => {
  it("generates an architecture reflection from a real workspace", () => {
    const workspace = new Workspace(root);
    const config = workspace.init("demo");
    const store = new EventStore(workspace.dbPath);
    try {
      store.appendArchitectureShift(architectureShift(config.projectId));
    } finally {
      store.close();
    }

    const report = runReflect("architecture", { limit: 2 }, root);
    const output = renderReflectionReport(report);

    expect(report.items[0]).toMatchObject({
      title: "CLI reflection boundary",
      citations: expect.arrayContaining([
        expect.objectContaining({ reference: "architecture:11111111-1111-4111-8111-111111111111" }),
      ]),
    });
    expect(output).toContain("Architecture reflection");
    expect(output).toContain("CLI reflection boundary");
  });

  it("rejects unsupported reflection modes", () => {
    const workspace = new Workspace(root);
    workspace.init("demo");

    expect(() => runReflect("unknown", {}, root)).toThrow("Unsupported reflection mode");
  });
});

function architectureShift(projectId: string): ArchitectureShift {
  return {
    id: "11111111-1111-4111-8111-111111111111",
    projectId,
    detectedAt: "2026-05-31T09:20:00.000Z",
    kind: "modularization",
    title: "CLI reflection boundary",
    summary: "Reflection output is generated by core and rendered by the CLI.",
    affectedPaths: ["apps/cli/src/commands/reflect.ts", "packages/core/src/reflect"],
    relatedSessionIds: [],
  };
}
