import type { ProviderSetup } from "./provider.ts";

const PROVIDERS: ProviderSetup[] = [
  {
    name: "openai",
    label: "OpenAI",
    apiKeyEnv: "OPENAI_API_KEY",
    baseUrl: "https://api.openai.com/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "anthropic",
    label: "Anthropic",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    baseUrl: "https://api.anthropic.com",
    status: "supported",
    auth: "API key in x-api-key header",
    headlessAuth: "Workload Identity Federation",
  },
  {
    name: "gemini",
    label: "Gemini API",
    apiKeyEnv: "GEMINI_API_KEY",
    baseUrl: "https://generativelanguage.googleapis.com",
    status: "supported",
    auth: "API key",
    headlessAuth: null,
  },
  {
    name: "openrouter",
    label: "OpenRouter",
    apiKeyEnv: "OPENROUTER_API_KEY",
    baseUrl: "https://openrouter.ai/api/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: "OAuth",
  },
  {
    name: "ollama",
    label: "Ollama",
    apiKeyEnv: null,
    baseUrl: "http://localhost:11434",
    status: "supported",
    auth: "Local daemon, no API key by default",
    headlessAuth: null,
  },
  {
    name: "amazon-bedrock",
    label: "Amazon Bedrock",
    apiKeyEnv: "BEDROCK_API_KEY",
    baseUrl: "https://bedrock-mantle.<region>.api.aws/v1",
    status: "supported",
    auth: "Short-term API key",
    headlessAuth: "IAM roles or temporary credentials",
  },
  {
    name: "azure-openai",
    label: "Azure OpenAI",
    apiKeyEnv: "AZURE_OPENAI_API_KEY",
    baseUrl: null,
    status: "planned",
    auth: "API key",
    headlessAuth: "Microsoft Entra ID",
  },
  {
    name: "cerebras",
    label: "Cerebras",
    apiKeyEnv: "CEREBRAS_API_KEY",
    baseUrl: "https://api.cerebras.ai/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "cohere",
    label: "Cohere",
    apiKeyEnv: "COHERE_API_KEY",
    baseUrl: "https://api.cohere.com",
    status: "planned",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "custom",
    label: "Custom OpenAI-compatible",
    apiKeyEnv: "KAIRO_AI_API_KEY",
    baseUrl: null,
    status: "supported",
    auth: "Configurable API key header through OpenAI-compatible bearer auth",
    headlessAuth: null,
  },
  {
    name: "deepseek",
    label: "DeepSeek",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    baseUrl: "https://api.deepseek.com",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "fireworks",
    label: "Fireworks AI",
    apiKeyEnv: "FIREWORKS_API_KEY",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "groq",
    label: "Groq",
    apiKeyEnv: "GROQ_API_KEY",
    baseUrl: "https://api.groq.com/openai/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "kilo",
    label: "Kilo Gateway",
    apiKeyEnv: "KILO_API_KEY",
    baseUrl: "https://api.kilo.ai/api/gateway",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "lm-studio",
    label: "LM Studio",
    apiKeyEnv: "LM_STUDIO_API_KEY",
    baseUrl: "http://localhost:1234/v1",
    status: "supported",
    auth: "Local OpenAI-compatible server; API key optional",
    headlessAuth: null,
  },
  {
    name: "minimax",
    label: "MiniMax",
    apiKeyEnv: "MINIMAX_API_KEY",
    baseUrl: "https://api.minimax.io/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "mistral",
    label: "Mistral",
    apiKeyEnv: "MISTRAL_API_KEY",
    baseUrl: "https://api.mistral.ai/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "moonshot",
    label: "Moonshot Kimi",
    apiKeyEnv: "MOONSHOT_API_KEY",
    baseUrl: "https://api.moonshot.ai/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "perplexity",
    label: "Perplexity",
    apiKeyEnv: "PERPLEXITY_API_KEY",
    baseUrl: "https://api.perplexity.ai",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "together",
    label: "Together AI",
    apiKeyEnv: "TOGETHER_API_KEY",
    baseUrl: "https://api.together.xyz/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
  {
    name: "vertex-ai",
    label: "Vertex AI",
    apiKeyEnv: null,
    baseUrl: null,
    status: "planned",
    auth: "Google Cloud credentials",
    headlessAuth: "Application Default Credentials",
  },
  {
    name: "xai",
    label: "xAI Grok",
    apiKeyEnv: "XAI_API_KEY",
    baseUrl: "https://api.x.ai/v1",
    status: "supported",
    auth: "API key bearer token",
    headlessAuth: null,
  },
];

export function listProviderSetups(): ProviderSetup[] {
  return [...PROVIDERS];
}
